"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { FileOutput, Calendar, Bot } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { EASE_OUT_SMOOTH } from "@/lib/utils";

interface Output {
  id: string;
  title: string;
  type: string;
  agent: string;
  createdAt: string;
}

const OUTPUTS_KEY = "agency-outputs";

const fadeUp = {
  hidden: { opacity: 0, y: 12 },
  show: { opacity: 1, y: 0, transition: { duration: 0.4, ease: EASE_OUT_SMOOTH as any } },
};

const stagger = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.05 } },
};

export default function OutputsPage() {
  const [outputs, setOutputs] = useState<Output[]>([]);

  useEffect(() => {
    try {
      setOutputs(JSON.parse(localStorage.getItem(OUTPUTS_KEY) || "[]"));
    } catch {}
  }, []);

  return (
    <motion.div initial="hidden" animate="show" variants={stagger} className="space-y-6">
      <motion.div variants={fadeUp}>
        <h2 className="text-2xl font-bold text-[hsl(var(--foreground))]">Outputs</h2>
        <p className="mt-1 text-[hsl(var(--muted-foreground))]">
          All deliverables generated by your agency.
        </p>
      </motion.div>

      <motion.div variants={fadeUp}>
        <Card glass className="p-12">
          <div className="flex flex-col items-center text-center">
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[hsl(var(--primary)/0.1)] mb-4">
              <FileOutput className="h-8 w-8 text-[hsl(var(--primary))]" />
            </div>
            <h3 className="text-lg font-semibold text-[hsl(var(--foreground))]">
              {outputs.length === 0 ? "No outputs yet" : `${outputs.length} deliverables`}
            </h3>
            <p className="mt-2 max-w-sm text-sm text-[hsl(var(--muted-foreground))]">
              Outputs appear here when you ask the agency to create content, reports,
              strategies, or any other deliverables through the chat.
            </p>
          </div>
        </Card>
      </motion.div>

      {outputs.length > 0 && (
        <motion.div variants={stagger} className="space-y-3">
          {outputs.map((output) => (
            <motion.div key={output.id} variants={fadeUp}>
              <Card glass className="transition-all hover:border-[hsl(var(--primary)/0.3)]">
                <CardContent className="flex items-center gap-4 p-4">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[hsl(var(--primary)/0.1)]">
                    <FileOutput className="h-5 w-5 text-[hsl(var(--primary))]" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-[hsl(var(--foreground))]">{output.title}</p>
                    <div className="flex items-center gap-3 mt-1 text-xs text-[hsl(var(--muted-foreground))]">
                      <span className="flex items-center gap-1"><Bot className="h-3 w-3" /> {output.agent}</span>
                      <span className="flex items-center gap-1"><Calendar className="h-3 w-3" /> {output.createdAt}</span>
                    </div>
                  </div>
                  <span className="rounded-md bg-[hsl(var(--muted))] px-2 py-0.5 text-xs text-[hsl(var(--muted-foreground))]">{output.type}</span>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </motion.div>
      )}
    </motion.div>
  );
}
